@ECHO OFF
CLS
@ECHO "Boot Camp: Be all that you can be!"
@ECHO.
@ECHO.
@ECHO "Death Dominos..."
PAUSE
DOOM -FILE BOOTCAMP.WAD -NOMONSTERS -PLAYDEMO BC1 -NOJOY
CLS
@ECHO "Target Practice..."
PAUSE
DOOM -FILE BOOTCAMP.WAD -NOMONSTERS -PLAYDEMO BC2 -NOJOY
CLS
@ECHO "Battle your favorite ghoul!"
PAUSE
DOOM -FILE BOOTCAMP.WAD -PLAYDEMO BC3 -NOJOY
CLS
@ECHO "Shoot it out with your pistol or try hand-to-hand combat"
@ECHO "in the Deathmatch Arena... Monster or MP mode."
PAUSE
DOOM -FILE BOOTCAMP.WAD -PLAYDEMO BC4 -NOJOY
CLS
@ECHO "Try your luck in the All Monster Death Arena (mine isn't so good)!"
PAUSE
DOOM -FILE BOOTCAMP.WAD -PLAYDEMO BC5 -NOJOY
CLS
@ECHO "Have a BLAST!- `Weeds'"