@echo off
echo Backing up Demon graphics
md sarga
dmgraph SARGA1 -e sarga\sarga1.gif
dmgraph SARGA2A8 -e sarga\sarga2a8.gif
dmgraph SARGA3A7 -e sarga\sarga3a7.gif
dmgraph SARGA4A6 -e sarga\sarga4a6.gif
dmgraph SARGA5 -e sarga\sarga5.gif
dmgraph SARGB1 -e sarga\sargb1.gif
dmgraph SARGB2B8 -e sarga\sargb2b8.gif
dmgraph SARGB3B7 -e sarga\sargb3b7.gif
dmgraph SARGB4B6 -e sarga\sargb4b6.gif
dmgraph SARGB5 -e sarga\sargb5.gif
dmgraph SARGC1 -e sarga\sargc1.gif
dmgraph SARGC2C8 -e sarga\sargc2c8.gif
dmgraph SARGC3C7 -e sarga\sargc3c7.gif
dmgraph SARGC4C6 -e sarga\sargc4c6.gif
dmgraph SARGC5 -e sarga\sargc5.gif
dmgraph SARGD1 -e sarga\sargd1.gif
dmgraph SARGD2D8 -e sarga\sargd2d8.gif
dmgraph SARGD3D7 -e sarga\sargd3d7.gif
dmgraph SARGD4D6 -e sarga\sargd4d6.gif
dmgraph SARGD5 -e sarga\sargd5.gif
dmgraph SARGE1 -e sarga\sarge1.gif
dmgraph SARGE2 -e sarga\sarge2.gif
dmgraph SARGE3 -e sarga\sarge3.gif
dmgraph SARGE4 -e sarga\sarge4.gif
dmgraph SARGE5 -e sarga\sarge5.gif
dmgraph SARGE6 -e sarga\sarge6.gif
dmgraph SARGE7 -e sarga\sarge7.gif
dmgraph SARGE8 -e sarga\sarge8.gif
dmgraph SARGF1 -e sarga\sargf1.gif
dmgraph SARGF2 -e sarga\sargf2.gif
dmgraph SARGF3 -e sarga\sargf3.gif
dmgraph SARGF4 -e sarga\sargf4.gif
dmgraph SARGF5 -e sarga\sargf5.gif
dmgraph SARGF6 -e sarga\sargf6.gif
dmgraph SARGF7 -e sarga\sargf7.gif
dmgraph SARGF8 -e sarga\sargf8.gif
dmgraph SARGG1 -e sarga\sargg1.gif
dmgraph SARGG2 -e sarga\sargg2.gif
dmgraph SARGG3 -e sarga\sargg3.gif
dmgraph SARGG4 -e sarga\sargg4.gif
dmgraph SARGG5 -e sarga\sargg5.gif
dmgraph SARGG6 -e sarga\sargg6.gif
dmgraph SARGG7 -e sarga\sargg7.gif
dmgraph SARGG8 -e sarga\sargg8.gif
dmgraph SARGH1 -e sarga\sargh1.gif
dmgraph SARGH2 -e sarga\sargh2.gif
dmgraph SARGH3 -e sarga\sargh3.gif
dmgraph SARGH4 -e sarga\sargh4.gif
dmgraph SARGH5 -e sarga\sargh5.gif
dmgraph SARGH6 -e sarga\sargh6.gif
dmgraph SARGH7 -e sarga\sargh7.gif
dmgraph SARGH8 -e sarga\sargh8.gif
dmgraph SARGI0 -e sarga\sargi0.gif
dmgraph SARGJ0 -e sarga\sargj0.gif
dmgraph SARGK0 -e sarga\sargk0.gif
dmgraph SARGL0 -e sarga\sargl0.gif
dmgraph SARGM0 -e sarga\sargm0.gif
dmgraph SARGN0 -e sarga\sargn0.gif


echo Getting Plasma Monster Graphics

dmgraph bfs1a0 -e sarga\bfs1a0.gif
dmgraph bfs1b0 -e sarga\bfs1b0.gif

dmgraph bfe1a0 -e sarga\bfe1a0.gif
dmgraph bfe1b0 -e sarga\bfe1b0.gif
dmgraph bfe1c0 -e sarga\bfe1c0.gif
dmgraph bfe1d0 -e sarga\bfe1d0.gif
dmgraph bfe1e0 -e sarga\bfe1e0.gif



echo Putting Plasma Monster Graphics in

dmgraph SARGA1 -s sarga\bfs1a0.gif
dmgraph SARGA2A8 -s sarga\bfs1b0.gif
dmgraph SARGA3A7 -s sarga\bfs1a0.gif
dmgraph SARGA4A6 -s sarga\bfs1b0.gif
dmgraph SARGA5 -s sarga\bfs1a0.gif
dmgraph SARGB1 -s sarga\bfs1b0.gif
dmgraph SARGB2B8 -s sarga\bfs1a0.gif
dmgraph SARGB3B7 -s sarga\bfs1b0.gif
dmgraph SARGB4B6 -s sarga\bfs1a0.gif
dmgraph SARGB5 -s sarga\bfs1b0.gif
dmgraph SARGC1 -s sarga\bfs1a0.gif
dmgraph SARGC2C8 -s sarga\bfs1b0.gif
dmgraph SARGC3C7 -s sarga\bfs1a0.gif
dmgraph SARGC4C6 -s sarga\bfs1b0.gif
dmgraph SARGC5 -s sarga\bfs1a0.gif
dmgraph SARGD1 -s sarga\bfs1b0.gif
dmgraph SARGD2D8 -s sarga\bfs1a0.gif
dmgraph SARGD3D7 -s sarga\bfs1b0.gif
dmgraph SARGD4D6 -s sarga\bfs1a0.gif
dmgraph SARGD5 -s sarga\bfs1b0.gif
dmgraph SARGE1 -s sarga\bfs1a0.gif
dmgraph SARGE2 -s sarga\bfs1b0.gif
dmgraph SARGE3 -s sarga\bfs1a0.gif
dmgraph SARGE4 -s sarga\bfs1b0.gif
dmgraph SARGE5 -s sarga\bfs1a0.gif
dmgraph SARGE6 -s sarga\bfs1b0.gif
dmgraph SARGE7 -s sarga\bfs1a0.gif
dmgraph SARGE8 -s sarga\bfs1b0.gif
dmgraph SARGF1 -s sarga\bfs1a0.gif
dmgraph SARGF2 -s sarga\bfs1b0.gif
dmgraph SARGF3 -s sarga\bfs1a0.gif
dmgraph SARGF4 -s sarga\bfs1b0.gif
dmgraph SARGF5 -s sarga\bfs1a0.gif
dmgraph SARGF6 -s sarga\bfs1b0.gif
dmgraph SARGF7 -s sarga\bfs1a0.gif
dmgraph SARGF8 -s sarga\bfs1b0.gif
dmgraph SARGG1 -s sarga\bfs1a0.gif
dmgraph SARGG2 -s sarga\bfs1b0.gif
dmgraph SARGG3 -s sarga\bfs1a0.gif
dmgraph SARGG4 -s sarga\bfs1b0.gif
dmgraph SARGG5 -s sarga\bfs1a0.gif
dmgraph SARGG6 -s sarga\bfs1b0.gif
dmgraph SARGG7 -s sarga\bfs1a0.gif
dmgraph SARGG8 -s sarga\bfs1b0.gif
dmgraph SARGH1 -s sarga\bfs1a0.gif
dmgraph SARGH2 -s sarga\bfs1b0.gif
dmgraph SARGH3 -s sarga\bfs1a0.gif
dmgraph SARGH4 -s sarga\bfs1b0.gif
dmgraph SARGH5 -s sarga\bfs1a0.gif
dmgraph SARGH6 -s sarga\bfs1b0.gif
dmgraph SARGH7 -s sarga\bfs1a0.gif
dmgraph SARGH8 -s sarga\bfs1b0.gif
dmgraph SARGI0 -s sarga\bfs1a0.gif
dmgraph SARGJ0 -s sarga\bfs1b0.gif
dmgraph SARGK0 -s sarga\bfs1a0.gif
dmgraph SARGL0 -s sarga\bfs1b0.gif
dmgraph SARGM0 -s sarga\bfs1a0.gif
dmgraph SARGN0 -s sarga\bfs1b0.gif


echo Pulling old Barrel Explosion Graphics

dmgraph bexpa0 -e sarga\bexpa0.gif
dmgraph bexpb0 -e sarga\bexpb0.gif
dmgraph bexpc0 -e sarga\bexpc0.gif
dmgraph bexpd0 -e sarga\bexpd0.gif
dmgraph bexpe0 -e sarga\bexpe0.gif

echo Inserting new Barrel Explosion Graphics

dmgraph bexpa0 -s sarga\bfe1a0.gif
dmgraph bexpb0 -s sarga\bfe1b0.gif
dmgraph bexpc0 -s sarga\bfe1c0.gif
dmgraph bexpd0 -s sarga\bfe1d0.gif
dmgraph bexpe0 -s sarga\bfe1e0.gif
                  
echo Backing up DOOM.EXE
dehacked -save doomexe.deh

echo Inserting MINES
dehacked -load bmine.deh


echo Done 
echo -----Enjoy----

