@echo off
echo GGGGG RRRR   AAA  Y   Y M   M  AAA  TTTTT TTTTT EEEEE RRRR  '''   SSSS
echo G     R   R A   A Y   Y MM MM A   A   T     T   E     R   R '''  S
echo G  GG RRRR  AAAAA  Y Y  M M M AAAAA   T     T   EEE   RRRR    '   SSS
echo G   G R   R A   A   Y   M   M A   A   T     T   E     R   R          S
echo GGGGG R   R A   A   Y   M   M A   A   T     T   EEEEE R   R      SSSS
echo
echo      TTTTT  H   H  EEEEE      CCCC   OOO   FFFFF  FFFFF  I  N   N
echo        T    H   H  E         C      O   O  F      F      I  NN  N
echo        T    HHHHH  EEEE      C      O   O  FFFF   FFFF   I  N N N
echo        T    H   H  E         C      O   O  F      F      I  N  NN
echo        T    H   H  EEEEE      CCCC   OOO   F      F      I  N   N
doom -file coffin.wad -devparm -wart 2 1
