REM  *** backing up original floor and ceiling textures ***
dmgraph lava1 -e lava1.gif -t GIF
dmgraph lava2 -e lava2.gif -t GIF
dmgraph lava3 -e lava3.gif -t GIF
dmgraph lava4 -e lava4.gif -t GIF
dmgraph cratop1 -e cratop1.gif -t GIF
dmgraph ceil4_2 -e ceil4_2.gif -t GIF
dmgraph ceil5_2 -e ceil5_2.gif -t GIF
REM  *** inserting new floor and ceiling textures ***
dmgraph lava1 -s wormflo1.gif -t GIF
dmgraph lava2 -s wormflo3.gif -t GIF
dmgraph lava3 -s wormflo2.gif -t GIF
dmgraph lava4 -s wormflo3.gif -t GIF
dmgraph cratop1 -s crustile.gif -t GIF
dmgraph ceil4_2 -s metal1.gif -t GIF
dmgraph ceil5_2 -s metal2.gif -t GIF
